name: "postprocessing"
backend: "python"
max_batch_size: 4
input [
  {
    name: "output_ids"
    data_type: TYPE_UINT32
    dims: [ -1, -1 ]
  },
  {
    name: "sequence_length"
    data_type: TYPE_UINT32
    dims: [ -1 ]
  },
  {
    name: "cum_log_probs"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "output_log_probs"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [
    {
        count: 2
        kind: KIND_CPU
    }
]
